[package]
name = "backmon"
version = "0.1.0"
authors = ["abby <abby@kabu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.15"
nix = "0.19.1"
daemonize = "0.4.1"